{% set name = "pycp2k" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 460291dcf01a8f042e61bfbfa1526255877a6ef67242acc27b7eec2d8909839d
  patches: 
    - anaconda.patch

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pip
    - future
    - ase
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pycp2k
  commands:
    - pip check

about:
  home: https://github.com/SINGROUP/pycp2k
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Python Cp2k interface'

  description: |
    PYCP2K is a python package providing a dynamic object-oriented 
    interface to CP2K, an atomistic and molecular simulation software.
  doc_url: https://github.com/SINGROUP/pycp2k 
  dev_url: https://github.com/SINGROUP/pycp2k

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
