travis:
  secure:
    BINSTAR_TOKEN: IxSDrjAXMpk7U3sUMj529zlRvuJMgEN2NddPHZ8dpF0lI1l42pTUfIOlPhpp48TUSHCIfnOFA7JTDQ7/wAAFyU7vl/dL/BI5AtNF+FXpHiO3UzkYyTVn1WTDZWAJZLanOyBX/YiQUc9tpudIZmvokOM7CgJYbUHZOP/9+1vygWpq2KwP/N0xUPIdbeuHC8+8iZ3ejweC5pJ1328BMLrEabQ+7VLE8fm7ADtCESDsUR+MGcnT1HAFft5rb1Ps/SzEB6hAzudaQtga/Kt8+oWo3OmHaUNZI5TxHUoFvUH+aKWM3cCC8PwmzKMgYGDqeih1RbFSKlccuAbOt3GYbmVoyA2yan/KZeQNbovCjlBr0u9blbo2C9wuUM6Gcc89UGSUb+PqOi78LCrHNMtIUm4j9BOI6rWUexnrbr8IytrT57woZ1QFGENUw+pKo+hWyxPCe56SDSNcsIOZ6UV293k/VIkH/RcW19gR28NQd2ih/1Jx87pd3tQZidREPmRq/c2uv+VcXUOB6/j09YK3aQ916U7YYxpeKLmOA157yuh4eIoUkPCcRxo9e5vnM4VsplVTGC0nnIfyv2k26PrkFaLBzuttu8lPrThkUfU99bmpm11FCC+5O5iwBlLkBAmMUnjysIJWHnySo957eAzxvbBWCiULo29INsmwnkTxXkVdweM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
